package guiWithoutAction;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JMenuItem;

/**
 * Simplest example of GUI
 * 
 * @author tadaki
 */
public class Main extends javax.swing.JFrame {

    public enum ColorItem {//Define colors as an enum instance
        ORANGE(Color.ORANGE), YELLOW(Color.YELLOW), GREEN(Color.GREEN);
        private final Color color;

        ColorItem(Color color) {//Each color has a java.awt.color instance
            this.color = color;
        }

        public Color getColor() {
            return color;
        }
    }

    /**
     * Creates new form MainWithJMenu
     */
    public Main() {
        initComponents();//Init components defined by Design
        Font font = new Font("MS UI Gothic", 0, 24);
        for (ColorItem color : ColorItem.values()) {//Add colors to the menu
            JMenuItem item = new JMenuItem(color.toString());
            item.setFont(font);
            selectColors.add(item);//Add the item to the menu
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exit = new javax.swing.JMenuItem();
        selectColors = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("guiWithoutAction");
        setBackground(new java.awt.Color(204, 255, 204));

        menuBar.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N

        fileMenu.setText("File");
        fileMenu.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N

        exit.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        exit.setText("Exit");
        fileMenu.add(exit);

        menuBar.add(fileMenu);

        selectColors.setText("Colors");
        selectColors.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        menuBar.add(selectColors);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 262, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem exit;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu selectColors;
    // End of variables declaration//GEN-END:variables
}
