package guiWithAction;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JSlider;
import javax.swing.BorderFactory;

/**
 * Simple example of GUI with actions
 * 
 * @author tadaki
 */
public class Main extends javax.swing.JFrame {

    public enum ColorItem {//Define colors as enum instance
        ORANGE(Color.ORANGE), YELLOW(Color.YELLOW), GREEN(Color.GREEN);
        private final Color color;

        ColorItem(Color color) {//Each color has a java.awt.color instance
            this.color = color;
        }

        public Color getColor() {
            return color;
        }
    }
    private final JLabel label;
    private final JSlider slider;
    private final Font font;

    /**
     * Creates new form MainWithJMenu
     */
    public Main() {
        initComponents();
        font = new Font("MS UI Gothic", 0, 24);

        for (ColorItem color : ColorItem.values()) {//Add colors to the menu
            JMenuItem item = new JMenuItem(color.toString());
            item.setFont(font);
            //Add an action to the item
            item.addActionListener(e -> colorItemPerformed(color));
            selectColors.add(item);
        }

        //Create slider instance
        slider = new JSlider();
        slider.setFont(font);
        slider.setPaintTicks(true);
        slider.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        slider.setBackground(Color.white);
        //Define slider action
        slider.addChangeListener(e -> sliderStateChanged(e));
        menuBar.add(slider);//Add slider to the menu

        //Create label instance
        label = new JLabel();
        label.setFont(font);
        menuBar.add(label);//Add label to the menu

        int v = slider.getValue();
        label.setText(String.valueOf(v));
        pack();
    }

    /**
     * Action at color selection
     *
     * @param c
     */
    private void colorItemPerformed(ColorItem c) {
        System.out.println(c.toString());
        panel.setBackground(c.getColor());
    }

    /**
     * Action at slider operation
     *
     * @param evt
     */
    private void sliderStateChanged(javax.swing.event.ChangeEvent evt) {
        int v = slider.getValue();
        label.setText(String.valueOf(v));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exit = new javax.swing.JMenuItem();
        selectColors = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 200));
        setPreferredSize(new java.awt.Dimension(400, 200));

        panel.setMinimumSize(new java.awt.Dimension(100, 100));
        getContentPane().add(panel, java.awt.BorderLayout.CENTER);

        fileMenu.setText("File");
        fileMenu.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N

        exit.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        exit.setText("exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        fileMenu.add(exit);

        menuBar.add(fileMenu);

        selectColors.setText("Colors");
        selectColors.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        menuBar.add(selectColors);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        dispose();
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem exit;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JPanel panel;
    private javax.swing.JMenu selectColors;
    // End of variables declaration//GEN-END:variables
}
