package simpleTimer;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;

/**
 *
 * @author tadaki
 */
public class SimpleTimer extends javax.swing.JFrame {

    private final Timer timerLabel;
    private final Dimension timerDimension = new Dimension(400, 50);
    private final SetTimePanel setTimePanel;
    private Thread runner = null;
    private final Color foregroundNormal=Color.BLACK;
    private final Color foregroundOver = Color.RED;
    private final JToggleButton toggle;
    private final JButton setButton;

    /**
     * Creates new form SimpleTimer
     */
    public SimpleTimer() {
        initComponents();
        Font font = new Font("MS UI Gothic", 0, 24);

        //時間を表示するTimerクラスの生成と設置
        timerLabel = new Timer();
        timerLabel.setMaximumSize(timerDimension);
        timerLabel.setPreferredSize(timerDimension);
        timerLabel.setFont(font);
        timerLabel.setForegroundNormal(foregroundNormal);
        timerLabel.setForegroundOver(foregroundOver);
        showPanel.add(timerLabel);
        setTimePanel = new SetTimePanel();

        //START/STOPのトグルボタンの生成と配置
        toggle = new JToggleButton("START");
        toggle.setFont(font);
        toggle.addActionListener(evt -> toggleActionPerformed(evt));
        menuBar.add(toggle);

        //タイマーの設定のダイアログを起動するボタンの生成と配置
        setButton = new JButton("SET");
        setButton.setFont(font);
        setButton.addActionListener(e -> setTimeActionPerformed(e));
        menuBar.add(setButton);
        pack();
    }

    /**
     * START/STOP トグルボタンの動作
     *
     * @param evt
     */
    private void toggleActionPerformed(java.awt.event.ActionEvent evt) {
        boolean isRunning = toggle.isSelected();
        if (isRunning) {
            toggle.setText("STOP");
            timerLabel.start();
            runner = new Thread(timerLabel);
            runner.start();
        } else {
            toggle.setText("START");
            timerLabel.stop();
        }
        pack();
    }

    /**
     * SET ボタンの動作
     *
     * @param evt
     */
    private void setTimeActionPerformed(java.awt.event.ActionEvent evt) {
        //停止する
        toggle.setSelected(false);
        toggle.setText("START");
        timerLabel.stop();
        //設定用Dialogの表示
        int answer = JOptionPane.showOptionDialog(new JFrame(), setTimePanel,
                "時間設定", JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, null, null);
        if (answer == JOptionPane.OK_OPTION) {
            //OKが押されたときに、制限時間を設定
            int m = setTimePanel.getMinute();
            int s = setTimePanel.getSecond();
            timerLabel.setMax(60 * m + s);
        } else {
            setTimePanel.setDefault();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        showPanel = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        quitMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        showPanel.setBackground(new java.awt.Color(204, 255, 204));
        getContentPane().add(showPanel, java.awt.BorderLayout.CENTER);

        fileMenu.setText("File");
        fileMenu.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N

        quitMenu.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        quitMenu.setText("Quit");
        quitMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitMenuActionPerformed(evt);
            }
        });
        fileMenu.add(quitMenu);

        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quitMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitMenuActionPerformed
        dispose();
    }//GEN-LAST:event_quitMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimpleTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimpleTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimpleTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimpleTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimpleTimer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem quitMenu;
    private javax.swing.JPanel showPanel;
    // End of variables declaration//GEN-END:variables
}
